// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-campaigns.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_campaigns_default = defineTool({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List the signed-in user's proposal campaigns (id, name, client, status, markets, flight dates).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max campaigns to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("campaigns").select(
      "id, campaign_name, client_name, status, markets, flight_start, flight_end, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-campaign.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_campaign_default = defineTool2({
  name: "get_campaign",
  title: "Get campaign",
  description: "Get the full record for one of the signed-in user's campaigns, including flight and option dates, markets, and portal status.",
  inputSchema: {
    campaign_id: z2.string().uuid().describe("Campaign UUID (from list_campaigns).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaign_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("campaigns").select("*").eq("id", campaign_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Campaign not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { campaign: data }
    };
  }
});

// src/lib/mcp/tools/list-units.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_units_default = defineTool3({
  name: "list_units",
  title: "List units for a campaign",
  description: "List billboard/media units for a campaign belonging to the signed-in user. Includes unit number, market, vendor, size, four-week rate and impressions, and highlights.",
  inputSchema: {
    campaign_id: z3.string().uuid().describe("Campaign UUID."),
    included_only: z3.boolean().optional().describe("If true, return only units marked included in the proposal."),
    limit: z3.number().int().min(1).max(500).optional().describe("Max units. Default 200.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaign_id, included_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("units").select(
      "id, unit_number, market, city, vendor, size, format, media_type, location_description, four_week_impressions, negotiated_rate_4wk, four_week_periods, total_cost, highlights, tier_a, tier_b, tier_c, included, recommended"
    ).eq("campaign_id", campaign_id).order("row_index", { ascending: true, nullsFirst: false }).limit(limit ?? 200);
    if (included_only) q = q.eq("included", true);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { units: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/campaign-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var campaign_summary_default = defineTool4({
  name: "campaign_summary",
  title: "Summarize a campaign",
  description: "Return aggregate metrics for a campaign: included unit count, market breakdown, vendor breakdown, total four-week impressions, and total campaign cost (with the campaign margin already applied).",
  inputSchema: {
    campaign_id: z4.string().uuid().describe("Campaign UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaign_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data: campaign, error: cErr } = await sb.from("campaigns").select("id, campaign_name, client_name, margin_pct, markets").eq("id", campaign_id).maybeSingle();
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    if (!campaign)
      return { content: [{ type: "text", text: "Campaign not found" }], isError: true };
    const { data: units, error: uErr } = await sb.from("units").select(
      "market, vendor, four_week_impressions, negotiated_rate_4wk, four_week_periods, included"
    ).eq("campaign_id", campaign_id);
    if (uErr) return { content: [{ type: "text", text: uErr.message }], isError: true };
    const margin = 1 + (Number(campaign.margin_pct ?? 0) || 0) / 100;
    const included = (units ?? []).filter((u) => u.included !== false);
    const byMarket = {};
    const byVendor = {};
    let totalImpressions = 0;
    let totalCost = 0;
    for (const u of included) {
      byMarket[u.market ?? "Unknown"] = (byMarket[u.market ?? "Unknown"] ?? 0) + 1;
      byVendor[u.vendor ?? "Unknown"] = (byVendor[u.vendor ?? "Unknown"] ?? 0) + 1;
      totalImpressions += Number(u.four_week_impressions ?? 0) || 0;
      const rate = Number(u.negotiated_rate_4wk ?? 0) || 0;
      const periods = Number(u.four_week_periods ?? 1) || 1;
      totalCost += rate * margin * periods;
    }
    const summary = {
      campaign_id: campaign.id,
      campaign_name: campaign.campaign_name,
      client_name: campaign.client_name,
      margin_pct: campaign.margin_pct,
      included_unit_count: included.length,
      total_unit_count: (units ?? []).length,
      by_market: byMarket,
      by_vendor: byVendor,
      total_four_week_impressions: totalImpressions,
      total_campaign_cost: Math.round(totalCost * 100) / 100
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ncwoxgpmakrhejzbfqcr";
var mcp_default = defineMcp({
  name: "coastal-maverick-mcp",
  title: "Coastal Maverick Proposal Generator",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's billboard proposal campaigns. Use list_campaigns to discover campaigns, get_campaign for full details, list_units for the media units in a campaign, and campaign_summary for aggregate metrics (unit counts, impressions, total cost with margin applied).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_campaigns_default, get_campaign_default, list_units_default, campaign_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
